version: '3.8'
services:
  mysqldb:
    image: mysql:latest
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=mybooksdb
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  backend:
    container_name: mybooks-backend-container
    build:
      context: infra
      target: production
    image: mybooks-backend
    depends_on:
      - mysqldb
    ports:
      - 8080:8080
    environment:
      NODE_ENV: production
      DB_HOST: mysqldb
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: secret
      DB_NAME: mybooksdb
    links:
      - db
    volumes:
      - ./:/src
  frontend:
    container_name: mybooks-frontend-container
    build:
      context: infra
      target: production
    image: mybooks-frontend
    depends_on:
      - mysqldb
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
      DB_HOST: mysqldb
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: secret
      DB_NAME: mybooksdb
    links:
      - db
    volumes:
      - ./:/src
volumes:
  db:
    driver: local